[package]
name = "backend-for-website"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["macros"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.5"
tonic = "0.14"
prost = "0.14"
tonic-prost = "0.14"
validator = { version = "0.21", features = ["derive"] }
regex = "1.13.1"
axum-cookie = "0.3.0"

[build-dependencies]
tonic-prost-build = "0.14"
