services:
  identity: "http://host.docker.internal:9543"
  music_catalog: "http://host.docker.internal:7878"
  music_storage: "http://host.docker.internal:9832"
  social: "http://host.docker.internal:7987"

auth:
  access_token_expiration_time: 15min
  refresh_token_expiration_time: 168h