syntax = "proto3";

package auth;

service Auth {
    rpc Login(UserId) returns (Tokens) {}
    rpc RefreshTokens(RefreshToken) returns (Tokens) {}
    rpc ExtractUserId(AccessToken) returns (UserId) {}
    rpc Logout(RefreshToken) returns (Empty) {}
}

message Empty {}

message Tokens {
    string access_token = 1;
    string refresh_token = 2;
}

message RefreshToken {
    string refresh_token = 1;
}

message AccessToken {
    string access_token = 1;
}

message UserId {
    int64 user_id = 1;
}